### ISSUE TITLE
Required status checks break release commit to main 

### ISSUE THREAD

**Issue by morey-tech** [argocd-diff-action/argocd-diff-action#18]
https://github.com/argocd-diff-action/argocd-diff-action/actions/runs/4471011296/jobs/7855326713#step:7:138

```
[5:17:49 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: git push --tags https://github.com/argocd-diff-action/argocd-diff-action.git HEAD:main
Error: Error: Command failed with exit code 1: git push --tags https://github.com/argocd-diff-action/argocd-diff-action.git HEAD:main
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: 3 of 3 required status checks are expected.        
To https://github.com/argocd-diff-action/argocd-diff-action.git
 ! [remote rejected] HEAD -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/argocd-diff-action/argocd-diff-action.git'
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: 3 of 3 required status checks are expected.        
To https://github.com/argocd-diff-action/argocd-diff-action.git
 ! [remote rejected] HEAD -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/argocd-diff-action/argocd-diff-action.git'
    at makeError (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async push (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/@semantic-release/git/lib/git.js:51:3)
    at async module.exports (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/@semantic-release/git/lib/prepare.js:69:5)
    at async prepare (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/@semantic-release/git/index.js:28:3)
    at async validator (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as prepare] (/home/runner/work/_actions/cycjimmy/semantic-release-action/v3/node_modules/semantic-release/lib/plugins/index.js:80:11) {
  shortMessage: 'Command failed with exit code 1: git push --tags https://github.com/argocd-diff-action/argocd-diff-action.git HEAD:main',
  command: 'git push --tags https://github.com/argocd-diff-action/argocd-diff-action.git HEAD:main',
  escapedCommand: 'git push --tags "https://github.com/argocd-diff-action/argocd-diff-action.git" "HEAD:main"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'remote: error: GH006: Protected branch update failed for refs/heads/main.        \n' +
    'remote: error: 3 of 3 required status checks are expected.        \n' +
    'To [https://github.com/argocd-diff-action/argocd-diff-action.git\n](https://github.com/argocd-diff-action/argocd-diff-action.git/n)' +
    ' ! [remote rejected] HEAD -> main (protected branch hook declined)\n' +
    "error: failed to push some refs to 'https://github.com/argocd-diff-action/argocd-diff-action.git'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/git'
}
```
![Xnapper-2023-03-20-14 36 39](https://user-images.githubusercontent.com/4213435/226434994-f3cf1ff4-fe97-4f85-9fa8-a6427ffd1b9e.png)

**Comment by Voziv** [comment]
This is fixed using a github app that has permissions to bypass the status checks
