### ISSUE TITLE
 TypeError: Cannot read properties of null (reading 'filter') at AppCollection.filterByRepo

### ISSUE THREAD

**Issue by morey-tech** [argocd-diff-action/argocd-diff-action#29]
Reproduced an error similar to #4 in https://github.com/argocd-diff-action/argocd-diff-action/actions/runs/4472595007/jobs/7858943776?pr=23
```
 TypeError: Cannot read properties of null (reading 'filter')
    at AppCollection.filterByRepo (/home/runner/work/argocd-diff-action/argocd-diff-action/webpack:/argocd-diff-action/src/argocd/AppCollection.ts:17:1)
    at /home/runner/work/argocd-diff-action/argocd-diff-action/webpack:/argocd-diff-action/src/main.ts:132:1
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/argocd-diff-action/argocd-diff-action/webpack:/argocd-diff-action/src/main.ts:28:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: TypeError: Cannot read properties of null (reading 'filter')
```

_Originally posted by @morey-tech in https://github.com/argocd-diff-action/argocd-diff-action/issues/23#issuecomment-1476888276_

**Comment by morey-tech** [comment]
This is caused by the `AppCollection.apps` being null when trying to use `AppCollection.filterByRepo`.
```
Warning: Get App Collection
Warning: Filter App Collection
Error: appAllCollection.apps == null
TypeError: Cannot read properties of null (reading 'filter')
Error: TypeError: Cannot read properties of null (reading 'filter')
    at AppCollection.filterByRepo (/home/runner/work/argocd-diff-action/argocd-diff-action/webpack:/argocd-diff-action/src/argocd/AppCollection.ts:17:1)
    at /home/runner/work/argocd-diff-action/argocd-diff-action/webpack:/argocd-diff-action/src/main.ts:140:1
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/argocd-diff-action/argocd-diff-action/webpack:/argocd-diff-action/src/main.ts:28:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
https://github.com/argocd-diff-action/argocd-diff-action/actions/runs/4525486727/jobs/7970018092#step:5:12
